### ISSUE TITLE
Determinación del lenguaje de programación

### ISSUE THREAD

**Issue by NickyGon** [Los-ultimos/Los-ultimos#10]
Determinar las tecnologías y lenguajes a utilizar para el Front End
Determinar las tecnologías y lenguajes a utilizar para el Back End
Acordar opciones para el aprendizaje y dominio básico de las tecnologías y lenguajes del proyecto

**Comment by NickyGon** [comment]
Si bien estamos de acuerdo con programar en Angular y Node JS para el front end, estamos en dudas con las tecnologías para el back end y B.D.D. Hay que dialogar

**Comment by kpomier777** [comment]
escogimos angular por el manejo eficiente que tiene nuestro compañero
