### ISSUE TITLE
Creacion del front end del panel principal

### ISSUE THREAD

**Issue by NickyGon** [Los-ultimos/Los-ultimos#19]
Creación de la pantalla del panel principal
Establecer las secciones según las entidades (Animales, Atención Clínica, Decesos, Fichas Médicas)

**Comment by NickyGon** [comment]
La navegación se realizó de manera existosa, con pestañas según entidades principales (Animales, Atención Clínica, Decesos, Fichas Médicas)

**Comment by Benji8500** [comment]
Se logro hacer una interfaz responsiva, reactiva a cambios y atractiva visualmente
