### ISSUE TITLE
Creacion de base de datos de la aplicacion

### ISSUE THREAD

**Issue by NickyGon** [Los-ultimos/Los-ultimos#21]
Creacion de base de datos en MongoDB
Creación de las tablas según lo establecido (Animales, propietarios, carnets, fichas médícas, atención clínica, decesos)
Vinculación con MongoDB Atlas en la aplicación
Establecimiento de las tablas en los front-End

**Comment by NickyGon** [comment]
Se escogió MongoDB por la experiencia de un compañero y su facilidad de implementar en tiempo reducido

**Comment by Benji8500** [comment]
Mongo permitio crear una base de datos donde si existen relaciones pero no de una forma restrictiva como en SQL. Esto ayudo mucho a crear la base de datos de manera eficaz
