### ISSUE TITLE
Creacion del formulario de animales y dueños

### ISSUE THREAD

**Issue by NickyGon** [Los-ultimos/Los-ultimos#24]
Creacion del frontend del formulario de animal y dueño
Vinculación a la base de datos de mongodb
Vinculación a la pestaña de animales

**Comment by NickyGon** [comment]
Se realizó el front end. Esperando la vinculación con base de datos

**Comment by Benji8500** [comment]
Se termino de integrar y juntar con la base de datos, haciendo que el formulario sea funcional
