### ISSUE TITLE
Creación del formulario de ficha médica

### ISSUE THREAD

**Issue by NickyGon** [Los-ultimos/Los-ultimos#25]
Creación del front end del formulario de ficha médica
Vinculación a la base de datos del sistema
Vinculación a la pantalla de fichas médicas

**Comment by NickyGon** [comment]
Se realizó el front end. Esperando la vinculación con base de datos

**Comment by Benji8500** [comment]
Se termino de integrar y juntar con la base de datos, haciendo que el formulario sea funcional
