### ISSUE TITLE
Creación del formulario de decesos

### ISSUE THREAD

**Issue by NickyGon** [Los-ultimos/Los-ultimos#26]
Creación del frontend del formulario de decesos
Vinculación a la base de datos de mongodb
VInculación a la pantalla de decesos

**Comment by NickyGon** [comment]
Se realizó el front end. Esperando la vinculación con base de datos

**Comment by Benji8500** [comment]
Se termino de integrar y juntar con la base de datos, haciendo que el formulario sea funcional
