### ISSUE TITLE
Creación y organización de roles dentro del grupo

### ISSUE THREAD

**Issue by Benji8500** [Los-ultimos/Los-ultimos#3]
Dialogar con el equipo
Determinar qué roles cumplirá cada miembro

**Comment by NickyGon** [comment]
Dialogar con el equipo
Determinar qué roles cumplirá cada miembro

**Comment by NickyGon** [comment]
Dialogar con el equipo
Determinar qué roles cumplirá cada miembro

**Comment by NickyGon** [comment]
Dialogar con el equipo
Determinar qué roles cumplirá cada miembro

**Comment by NickyGon** [comment]
Dialogar con el equipo 
Determinar qué roles cumplirá cada miembro

**Comment by NickyGon** [comment]
> Dialogar con el equipo
> Determinar qué roles cumplirá cada miembro

**Comment by NickyGon** [comment]
> Dialogar con el equipo Determinar qué roles cumplirá cada miembro

**Comment by NickyGon** [comment]
> Dialogar con el equipo Determinar qué roles cumplirá cada miembro
