### ISSUE TITLE
Creación del formulario de registro de emails

### ISSUE THREAD

**Issue by NickyGon** [Los-ultimos/Los-ultimos#37]
Creación del front end del formulario de registro de emails
Vinculación a la base de datos del sistema
Vinculación a la pantalla de animales con el botón "enviar carnet por correo electrónico"

**Comment by NickyGon** [comment]
Se realizó el front end. Esperando la vinculación con base de datos

**Comment by Benji8500** [comment]
Se termino de integrar y juntar con la base de datos, haciendo que el formulario sea funcional
