### ISSUE TITLE
Maquetación del Proyecto

### ISSUE THREAD

**Issue by kpomier777** [Los-ultimos/Los-ultimos#6]
analizar el proyecto 
definir viabilidad

**Comment by NickyGon** [comment]
Definir los mockups
Realizar los mockups

**Comment by NickyGon** [comment]
El proyecto es viable para realizar, ya que requiere de muchos procedimientos tipo CRUD en DB más que en aspecto de la interfaz de usuario, y la fórmula de formularios para registro puede ser reciclada según los casos
