### ISSUE TITLE
Casos de uso

### ISSUE THREAD

**Issue by NickyGon** [Los-ultimos/Los-ultimos#7]
Determinar los usuarios a utilizar la app
Realizar los diagramas de casos de uso
Colocar los diagramas en la Wiki

**Comment by NickyGon** [comment]
Determinar los usuarios a utilizar la app
Realizar los diagramas de casos de uso

**Comment by NickyGon** [comment]
> Determinar los usuarios a utilizar la app Realizar los diagramas de casos de uso

**Comment by NickyGon** [comment]
Determinar los usuarios a utilizar la app 
Realizar los diagramas de casos de uso

**Comment by kpomier777** [comment]
los usuario que van a ser : personal administrativo, veterinario y registro
